/*
 * STM32F103C6_EXTI_Driver.h
 *
 *  Created on: Aug 10, 2022
 *      Author: Fam Ayman
 */

#ifndef INC_STM32F103C6_EXTI_DRIVER_H_
#define INC_STM32F103C6_EXTI_DRIVER_H_
#include "STM32F103C6_GPIO_Driver.h"
typedef struct
{
	uint16_t EXTI_Input_Line_Number;
	S_GPIO_t * GPIO_Port ;
	uint16_t GPIO_PIN ;
	uint8_t IVT_IRQ_Number ;

}S_EXTI_GPIO_Mapping_t;
typedef struct
{
	S_EXTI_GPIO_Mapping_t  EXTI_PIN; 	//Specifies the external interrupt GPIO mapping
									 	//This  parameter must be set based @ ref EXTI_define
	uint8_t Trigger_Case;			 	//Specifies Rising Or Falling Or both
										//This parameter must be set based on @ref EXTI_Trigger_define
	uint8_t IRQ_EN;						//Enable or Disable the EXTI IRQ (That will Enable 	IRQ Mask  in EXTI and also on The Niva C interrupt
										//This parameter must be based on @ref EXTI_IRQ_define
	void(* P_IRQ_CallBack)(void);		//Set the C Function which will be called once the iRQ happen
}S_EXTI_Pin_Config_t;



//@ref EXTI_IRQ_define


#define EXTI_IRQ_Enable			0
#define EXTI_IRQ_Disable		1


//@ref EXTI_Trigger_define
#define EXTI_Trigger_Rising			0
#define EXTI_Trigger_Falling		1
#define EXTI_Trigger_Both			2

//@ref Macros



//@ref EXTI_define
#define EXTI0	0
#define EXTI1	1
#define EXTI2	2
#define EXTI3	3
#define EXTI4	4
#define EXTI5	5
#define EXTI6	6
#define EXTI7	7
#define EXTI8	8
#define EXTI9	9
#define EXTI10	10
#define EXTI11	11
#define EXTI12	12
#define EXTI13	13
#define EXTI14	14
#define EXTI15	15




//EXTI0
#define EXTI0_PA0	(S_EXTI_GPIO_Mapping_t){EXTI0,GPIOA,GPIO_PIN_0,EXTI0_IRQ}
#define EXTI0_PB0	(S_EXTI_GPIO_Mapping_t){EXTI0,GPIOB,GPIO_PIN_0,EXTI0_IRQ}
#define EXTI0_PC0	(S_EXTI_GPIO_Mapping_t){EXTI0,GPIOC,GPIO_PIN_0,EXTI0_IRQ}
#define EXTI0_PD0	(S_EXTI_GPIO_Mapping_t){EXTI0,GPIOD,GPIO_PIN_0,EXTI0_IRQ}


//EXTI1
#define EXTI1_PA1	(S_EXTI_GPIO_Mapping_t){EXTI1,GPIOA,GPIO_PIN_1,EXTI1_IRQ}
#define EXTI1_PB1	(S_EXTI_GPIO_Mapping_t){EXTI1,GPIOB,GPIO_PIN_1,EXTI1_IRQ}
#define EXTI1_PC1	(S_EXTI_GPIO_Mapping_t){EXTI1,GPIOC,GPIO_PIN_1,EXTI1_IRQ}
#define EXTI1_PD1	(S_EXTI_GPIO_Mapping_t){EXTI1,GPIOD,GPIO_PIN_1,EXTI1_IRQ}


//EXTI2
#define EXTI2_PA2	(S_EXTI_GPIO_Mapping_t){EXTI2,GPIOA,GPIO_PIN_2,EXTI2_IRQ}
#define EXTI2_PB2	(S_EXTI_GPIO_Mapping_t){EXTI2,GPIOB,GPIO_PIN_2,EXTI2_IRQ}
#define EXTI2_PC2	(S_EXTI_GPIO_Mapping_t){EXTI2,GPIOC,GPIO_PIN_2,EXTI2_IRQ}
#define EXTI2_PD2	(S_EXTI_GPIO_Mapping_t){EXTI2,GPIOD,GPIO_PIN_2,EXTI2_IRQ}


//EXTI3
#define EXTI3_PA3	(S_EXTI_GPIO_Mapping_t){EXTI3,GPIOA,GPIO_PIN_3,EXTI3_IRQ}
#define EXTI3_PB3	(S_EXTI_GPIO_Mapping_t){EXTI3,GPIOB,GPIO_PIN_3,EXTI3_IRQ}
#define EXTI3_PC3	(S_EXTI_GPIO_Mapping_t){EXTI3,GPIOC,GPIO_PIN_3,EXTI3_IRQ}
#define EXTI3_PD3	(S_EXTI_GPIO_Mapping_t){EXTI3,GPIOD,GPIO_PIN_3,EXTI3_IRQ}


//EXTI4
#define EXTI4_PA4	(S_EXTI_GPIO_Mapping_t){EXTI4,GPIOA,GPIO_PIN_4,EXTI4_IRQ}
#define EXTI4_PB4	(S_EXTI_GPIO_Mapping_t){EXTI4,GPIOB,GPIO_PIN_4,EXTI4_IRQ}
#define EXTI4_PC4	(S_EXTI_GPIO_Mapping_t){EXTI4,GPIOC,GPIO_PIN_4,EXTI4_IRQ}
#define EXTI4_PD4	(S_EXTI_GPIO_Mapping_t){EXTI4,GPIOD,GPIO_PIN_4,EXTI4_IRQ}


//EXTI5
#define EXTI5_PA5	(S_EXTI_GPIO_Mapping_t){EXTI5,GPIOA,GPIO_PIN_5,EXTI5_IRQ}
#define EXTI5_PB5	(S_EXTI_GPIO_Mapping_t){EXTI5,GPIOB,GPIO_PIN_5,EXTI5_IRQ}
#define EXTI5_PC5	(S_EXTI_GPIO_Mapping_t){EXTI5,GPIOC,GPIO_PIN_5,EXTI5_IRQ}
#define EXTI5_PD5	(S_EXTI_GPIO_Mapping_t){EXTI5,GPIOD,GPIO_PIN_5,EXTI5_IRQ}


//EXTI6
#define EXTI6_PA6	(S_EXTI_GPIO_Mapping_t){EXTI6,GPIOA,GPIO_PIN_6,EXTI6_IRQ}
#define EXTI6_PB6	(S_EXTI_GPIO_Mapping_t){EXTI6,GPIOB,GPIO_PIN_6,EXTI6_IRQ}
#define EXTI6_PC6	(S_EXTI_GPIO_Mapping_t){EXTI6,GPIOC,GPIO_PIN_6,EXTI6_IRQ}
#define EXTI6_PD6	(S_EXTI_GPIO_Mapping_t){EXTI6,GPIOD,GPIO_PIN_6,EXTI6_IRQ}


//EXTI7
#define EXTI7_PA7	(S_EXTI_GPIO_Mapping_t){EXTI7,GPIOA,GPIO_PIN_7,EXTI7_IRQ}
#define EXTI7_PB7	(S_EXTI_GPIO_Mapping_t){EXTI7,GPIOB,GPIO_PIN_7,EXTI7_IRQ}
#define EXTI7_PC7	(S_EXTI_GPIO_Mapping_t){EXTI7,GPIOC,GPIO_PIN_7,EXTI7_IRQ}
#define EXTI7_PD7	(S_EXTI_GPIO_Mapping_t){EXTI7,GPIOD,GPIO_PIN_7,EXTI7_IRQ}


//EXTI8
#define EXTI8_PA8	(S_EXTI_GPIO_Mapping_t){EXTI8,GPIOA,GPIO_PIN_8,EXTI8_IRQ}
#define EXTI8_PB8	(S_EXTI_GPIO_Mapping_t){EXTI8,GPIOB,GPIO_PIN_8,EXTI8_IRQ}
#define EXTI8_PC8	(S_EXTI_GPIO_Mapping_t){EXTI8,GPIOC,GPIO_PIN_8,EXTI8_IRQ}
#define EXTI8_PD8	(S_EXTI_GPIO_Mapping_t){EXTI8,GPIOD,GPIO_PIN_8,EXTI8_IRQ}


//EXTI9
#define EXTI9_PA9	(S_EXTI_GPIO_Mapping_t){EXTI9,GPIOA,GPIO_PIN_9,EXTI9_IRQ}
#define EXTI9_PB9	(S_EXTI_GPIO_Mapping_t){EXTI9,GPIOB,GPIO_PIN_9,EXTI9_IRQ}
#define EXTI9_PC9	(S_EXTI_GPIO_Mapping_t){EXTI9,GPIOC,GPIO_PIN_9,EXTI9_IRQ}
#define EXTI9_PD9	(S_EXTI_GPIO_Mapping_t){EXTI9,GPIOD,GPIO_PIN_9,EXTI9_IRQ}


//EXTI10
#define EXTI10_PA10	(S_EXTI_GPIO_Mapping_t){EXTI10,GPIOA,GPIO_PIN_10,EXTI10_IRQ}
#define EXTI10_PB10	(S_EXTI_GPIO_Mapping_t){EXTI10,GPIOB,GPIO_PIN_10,EXTI10_IRQ}
#define EXTI10_PC10	(S_EXTI_GPIO_Mapping_t){EXTI10,GPIOC,GPIO_PIN_10,EXTI10_IRQ}
#define EXTI10_PD10	(S_EXTI_GPIO_Mapping_t){EXTI10,GPIOD,GPIO_PIN_10,EXTI10_IRQ}


//EXTI11
#define EXTI11_PA11	(S_EXTI_GPIO_Mapping_t){EXTI11,GPIOA,GPIO_PIN_11,EXTI11_IRQ}
#define EXTI11_PB11	(S_EXTI_GPIO_Mapping_t){EXTI11,GPIOB,GPIO_PIN_11,EXTI11_IRQ}
#define EXTI11_PC11	(S_EXTI_GPIO_Mapping_t){EXTI11,GPIOC,GPIO_PIN_11,EXTI11_IRQ}
#define EXTI11_PD11	(S_EXTI_GPIO_Mapping_t){EXTI11,GPIOD,GPIO_PIN_11,EXTI11_IRQ}


//EXTI12
#define EXTI12_PA12	(S_EXTI_GPIO_Mapping_t){EXTI12,GPIOA,GPIO_PIN_12,EXTI12_IRQ}
#define EXTI12_PB12	(S_EXTI_GPIO_Mapping_t){EXTI12,GPIOB,GPIO_PIN_12,EXTI12_IRQ}
#define EXTI12_PC12	(S_EXTI_GPIO_Mapping_t){EXTI12,GPIOC,GPIO_PIN_12,EXTI12_IRQ}
#define EXTI12_PD12	(S_EXTI_GPIO_Mapping_t){EXTI12,GPIOD,GPIO_PIN_12,EXTI12_IRQ}


//EXTI13
#define EXTI13_PA13	(S_EXTI_GPIO_Mapping_t){EXTI13,GPIOA,GPIO_PIN_13,EXTI13_IRQ}
#define EXTI13_PB13	(S_EXTI_GPIO_Mapping_t){EXTI13,GPIOB,GPIO_PIN_13,EXTI13_IRQ}
#define EXTI13_PC13	(S_EXTI_GPIO_Mapping_t){EXTI13,GPIOC,GPIO_PIN_13,EXTI13_IRQ}
#define EXTI13_PD13	(S_EXTI_GPIO_Mapping_t){EXTI13,GPIOD,GPIO_PIN_13,EXTI13_IRQ}


//EXTI14
#define EXTI14_PA14	(S_EXTI_GPIO_Mapping_t){EXTI14,GPIOA,GPIO_PIN_14,EXTI14_IRQ}
#define EXTI14_PB14	(S_EXTI_GPIO_Mapping_t){EXTI14,GPIOB,GPIO_PIN_14,EXTI14_IRQ}
#define EXTI14_PC14	(S_EXTI_GPIO_Mapping_t){EXTI14,GPIOC,GPIO_PIN_14,EXTI14_IRQ}
#define EXTI14_PD14	(S_EXTI_GPIO_Mapping_t){EXTI14,GPIOD,GPIO_PIN_14,EXTI14_IRQ}


//EXTI15
#define EXTI15_PA15	(S_EXTI_GPIO_Mapping_t){EXTI15,GPIOA,GPIO_PIN_15,EXTI15_IRQ}
#define EXTI15_PB15	(S_EXTI_GPIO_Mapping_t){EXTI15,GPIOB,GPIO_PIN_15,EXTI15_IRQ}
#define EXTI15_PC15	(S_EXTI_GPIO_Mapping_t){EXTI15,GPIOC,GPIO_PIN_15,EXTI15_IRQ}
#define EXTI15_PD15	(S_EXTI_GPIO_Mapping_t){EXTI15,GPIOD,GPIO_PIN_15,EXTI15_IRQ}



/*
* ===============================================
* APIs Supported by "MCAL EXTI DRIVER"
* ===============================================
*/

void MCAL_EXTI_GPIO_Init(S_EXTI_Pin_Config_t * EXTI_Config);
void MCAL_EXTI_GPIO_Update(S_EXTI_Pin_Config_t * EXTI_Config);
void MCAL_EXTI_GPIO_Reset(void);


#endif /* INC_STM32F103C6_EXTI_DRIVER_H_ */
