/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "STM32F103C6_GPIO_Driver.h"
#include "sTM32F103x8.h"
#include "STM32F103C6_EXTI_Driver.h"
#include "core_cm3.h"
#include "Scheduler.h"
Task_Ref  Task1,Task2,Task3,Task4;
unsigned char Task1LED= 0  ,Task2LED = 0 ,Task3LED = 0,Task4LED = 0;
Mutex_ref Mutex1 ;
unsigned char payload[3] = {1,2,3};
void task1()
{
	static int  count1 = 0;
	while(1)
	{
		//Task1 Code
		Task1LED ^=1;
		count1++;
		if(count1 == 100)
		{
			MYRTOS_AcquireMutex(&Mutex1, &Task1);
			MYRTOS_ActivateTask(&Task2);


		}
		if(count1 == 200)
		{
			count1 = 0;
		}
	}
}
void task2()
{
	static int  count2 = 0;
	while(1)
	{
		Task2LED ^=1;
		count2++;
		if(count2 == 100)
		{
			MYRTOS_ActivateTask(&Task3);

		}
		if(count2 == 200)
		{
			count2 = 0 ;
			MYRTOS_TerminateTask(&Task2);
		}
	}
}
void task3()
{
	static int count3 = 0;
	while(1)
	{
		Task3LED ^=1;
		count3++;

		if(count3 == 100)
		{
			MYRTOS_ActivateTask(&Task4);
		}
		if(count3 == 200)
		{
			count3 = 0;
			MYRTOS_TerminateTask(&Task3);
		}
	}


}
void task4()
{
	static int count4 = 0;
	while(1)
	{
		Task4LED ^=1;
		count4++;
		if(count4 == 3)
		{
			MYRTOS_AcquireMutex(&Mutex1, &Task4);
		}
		if(count4 == 200)
		{
			count4= 0;
			MYRTOS_ReleaseMutex(&Mutex1);
			MYRTOS_TerminateTask(&Task4);
		}
	}
}
int main(void)
{
	HW_init();
	MYRTOS_ERRORID err;
	if( MYRTOS_init() != NoError);
	//Task1
	Task1.Stack_Size = 1024;
	Task1.p_TaskEntry  = task1;
	Task1.priority = 4;
	strcpy(Task1.TaskName , "Task1");

	//Task2
	Task2.Stack_Size = 1024;
	Task2.p_TaskEntry  = task2;
	Task2.priority = 3;
	strcpy(Task1.TaskName , "Task2");

	//Task3

	Task3.Stack_Size = 1024;
	Task3.p_TaskEntry  = task3;
	Task3.priority = 2;
	strcpy(Task3.TaskName , "Task3");

	//Task 4

	Task4.Stack_Size = 1024;
	Task4.p_TaskEntry  = task4;
	Task4.priority = 1;
	strcpy(Task4.TaskName , "Task4");

	MYRTOS_Create_Task(&Task1);
	MYRTOS_Create_Task(&Task2);
	MYRTOS_Create_Task(&Task3);
	MYRTOS_Create_Task(&Task4);
	MYRTOS_ActivateTask(&Task1);

	MYRTOS_Start_OS();
	while(1)
	{

	}
}
